export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "@/style.css"
const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body>
      <AntdRegistry>{children}</AntdRegistry>
    </body>
  </html>
);

export default RootLayout;